# Generated by Django 4.2.1 on 2023-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='Liters_taken',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
