# Generated by Django 4.2.1 on 2023-09-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_delete_email_alter_fuel_liters_taken_alter_fuel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='receipt',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
